export const GET_PROJECTS_BEGIN = "GET_PROJECTS_BEGIN";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR";
export const SET_PROJECTS = "SET_PROJECTS";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
